### PR TITLE
Update to Architectury

### PR DESCRIPTION
**Pull request by KaptainWutax**
This PR converts the mod to Architectury so it can be compiled against both Forge and Fabric. I have ported everything such that it behaves the same except for:

- The config. I've replaced it with a simple GSON dump for now, but it misses comments and ranges. 

- The build/deployment gradle system. I have only implemented the minimum necessary to run and build the mod.

This is enough for me to be able to use the mod on fabric and I do not need the features stated above. If it is something you are interested in you may use this branch as a reference or push to it directly.

### CODE REVIEW

**Comment by MarkusBordihn** [comment]
First of all thanks a lot for the PR and all the work and time you spend in converting the mod to Fabric over Architectury.

In general for larger and non-trivial changes like this, you should open an issue to discuss this with the maintainers first.
Otherwise, you risk doing a lot of work for nothing!

In this case I already started working on the next version (rewrite with some improvements) of this mod, which will available for Fabric, Forge and NeoForge (without Architectury).

However because you already spend some time and effort for this PR, which I appreciated, I will review and test the changes and will release this as 1.20.1 version.

I assume it will take 1-2 weeks for me to review and test the changes, mostly because I'm never used Architectury so far.

**Comment by KaptainWutax** [comment]
I understand and appreciate the heads-up for future contributions. My primary motivation was to meet an immediate need of mine more than anything so no time has been wasted. I figured I should open a PR so you can, at the very least, reference it if you're interested in Architectury. No pressure!

**Review by MarkusBordihn — APPROVED** [review]

**Comment by MarkusBordihn** [comment]
I reviewed the code and run some tests on Fabric so far everything works as expected.

Unfortunately I'm not able to start the Forge version and get the following strange error:
```
[Architectury Transformer] Listening at D:\Temp\Github\BOs-Daily-Rewards\common\build\devlibs\daily_rewards-mc1.20.1-v5.3.0.custom-dev.jar
Exception in thread "main" java.lang.module.ResolutionException: Module org.slf4j.simple reads more than one module named cpw.mods.securejarhandler
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:129)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
```

Even with the cleanup version, I'm unable to launch Forge with a similar error:
```
[Architectury Transformer] Listening at D:\Projects\GitHub\MarkusBordihn\BOs-Daily-Rewards\BOs-Daily-Rewards - 1.20.1\common\build\devlibs\daily_rewards-mc1.20.1-v6.0.0.custom-dev.jar
Exception in thread "main" java.lang.module.ResolutionException: Module com.ibm.icu reads more than one module named cpw.mods.securejarhandler
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:722)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:298)
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:129)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
```

This is not so critical for myself, because I could only upload the Fabric version.
However in the case you have any idea why this happens let me know. ;)

**Comment by MarkusBordihn** [comment]
Never mind, seems that the latest Forge version has some issues here.
By downgrading the version I was able to run it without any issues.

Will prepare the releases and thanks again for your work on this. ;)

**Comment by KaptainWutax** [comment]
Sounds great! Glad you figured out the issue with the forge build, I forgot to test it.

**Pull request merged**
